###
POST http://localhost:4000/api/consumidor
Content-Type: application/json

{
    "nombre": "ssadada",
    "apellido": "Vedsdadda",
    "comuna": "Calera de Tango",
    "telefono": "595959",
    "correo": "elnachoescachondo@gmail.com",
    "contrasena": "123456",
    "direccion": "puticlub",
    "fechaNacimiento": "kcyoxd"
}

###
GET http://localhost:4000/api/consumidor

###
GET http://localhost:4000/api/consumidor/632b786701a94b5755fa9901

###
PATCH http://localhost:4000/api/consumidor/banear/6344c4153f3dc33d14153c9e

###
PATCH http://localhost:4000/api/consumidor/activar/6344c4153f3dc33d14153c9e

###
POST http://localhost:4000/api/consumidor/login
Content-Type: application/json

{
    "correo": "elnachoescachondo@gmail.com",
    "contrasena": "123456"
}