###
POST http://localhost:4000/api/consumidor
Content-Type: application/json

{
    "nombre": "ssadada",
    "apellido": "Vedsdadda",
    "comuna": "Calera de Tango",
    "telefono": "595959",
    "correo": "otros8@gmail.com",
    "contrasena": "123456",
    "direccion": "puticlub",
    "fechaNacimiento": "kcyoxd"
}

###
GET http://localhost:4000/api/consumidor

###
GET http://localhost:4000/api/consumidor/632513a0d9f2894092a1c96e

###
PATCH http://localhost:4000/api/consumidor/banear/632b68b72c9b54ba862204c5

###
POST http://localhost:4000/api/consumidor/login
Content-Type: application/json

{
    "correo": "otros7@gmail.com",
    "contrasena": "123456"
}