###
GET http://localhost:4000/api/descuento

###
POST http://localhost:4000/api/descuento
Content-Type: application/json

{
    "costoNuevo": "5000",
    "idPlan": "6356d8ed77ef1d91f6fda724",
    "fechaTermino": "1999/07/17"
}