###
POST http://localhost:4000/api/horario/
Content-Type: application/json

{
    "idTrabajador":"63743b78d785d2ffca7e774b",
    "horaIntervalos": "12:00-12:30"
}

###
GET http://localhost:4000/api/horario/63743b78d785d2ffca7e774b
