###
GET http://localhost:4000/api/plan

###
POST http://localhost:4000/api/plan
Content-Type: application/json

{
    "costo": "7000",
    "encabezado": "Oferton",
    "descripcion": "Lleva 1000 coins en 7 lukas",
    "cantidadCoins": "1000"
}

###
PUT http://localhost:4000/api/plan/635053010765deb4901281ef
Content-Type: application/json

{
    "costo": "6000",
    "encabezado": "Oferton",
    "descripcion": "Lleva 1000 coins en 6 lukas",
    "cantidadCoins": "1000"
}

###
DELETE  http://localhost:4000/api/plan/635053010765deb4901281ef

###
PUT http://localhost:4000/api/plan/crearDescuento/6356f685f4637d25684aab03
Content-Type: application/json

{
    "costoNuevo": "5000",
    "fechaTermino": "1999/07/17"
}