###
GET http://localhost:4000/api/trabajador

###
POST http://localhost:4000/api/trabajador
Content-Type: application/json

{
    "nombre": "ssadada",
    "apellido": "Vedsdadda",
    "comuna": "La Pintana",
    "genero": "Masculino",
    "telefono": "595959",
    "correo": "jaja@gmail.com",
    "contrasena": "123456",
    "rut": "111111-1",
    "direccion": "puticlub"
}