###
GET http://localhost:4000/api/trabajador

###
GET http://localhost:4000/api/trabajador/all

###
POST http://localhost:4000/api/trabajador
Content-Type: multipart/form-data

{
    "nombre": "ssadada",
    "apellido": "Vedsdadda",
    "comuna": "La Pintana",
    "solicitudPendiente": true, 
    "genero": "Masculino",
    "telefono": "595959",
    "correo": "alexisduoc01@gmail.com",
    "contrasena": "123456",
    "rut": "111111-1",
    "direccion": "mi casa",
    "activo": true,
    "fechaNacimiento": "24-04-2001",
}

###
PATCH http://localhost:4000/api/trabajador/aceptar/633de716ac61d21c94b5a6ec

###
PATCH http://localhost:4000/api/trabajador/rechazar/633de716ac61d21c94b5a6ec



###
GET http://localhost:4000/api/trabajador/perfil/634b4e5cdc7904138011938f